# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vbguest.auto_update = false
  #
  config.vm.provider "virtualbox" do |vb|
     # GUI activada para tener feedback
    vb.gui = true
  
     # cuanta memoria para la vm:
     vb.memory = "256"
   end
  
  # Habilite el aprovisionamiento con un script de shell. Aprovisionadores adicionales como
  # Puppet, Chef, Ansible, Salt y Docker también están disponibles. Por favor vea el
  # documentación para obtener más información sobre su sintaxis y uso específicos.
  # config.vm.provision "shell", en línea: << - SHELL
  # apt-get update
  # apt-get install -y apache2 graphite-web
  # SHELL
end
